version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        SERVER_PORT: ${SERVER_PORT}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_URI: ${MONGO_URI}
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        VITE_API_URL: ${VITE_API_URL}
        VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
        UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
    container_name: swe363_server
    ports:
      - "5000:5000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_URI: ${MONGO_URI}
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      VITE_API_URL: ${VITE_API_URL}
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
      UPLOADTHING_TOKEN: ${UPLOADTHING_TOKEN}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: swe363_client
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
      VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
